name: 'Release'

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - v*

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci: version bump to')"
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          token: ${{ secrets.github_token }}
      - run: cat package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
      - run: cat package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  release:
    needs: bump-version
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: prebuild
